---
name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - uses: pre-commit/action@v3.0.0
  test:
    name: Go tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -o ./dist/

      - name: Test
        uses: robherley/go-test-action@v0
        with:
          testArguments: -v ./ranger/...
